; Auto-generated. Do not edit!


(cl:in-package hello-msg)


;//! \htmlinclude demoFeedback.msg.html

(cl:defclass <demoFeedback> (roslisp-msg-protocol:ros-message)
  ((current_count
    :reader current_count
    :initarg :current_count
    :type cl:integer
    :initform 0))
)

(cl:defclass demoFeedback (<demoFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <demoFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'demoFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name hello-msg:<demoFeedback> is deprecated: use hello-msg:demoFeedback instead.")))

(cl:ensure-generic-function 'current_count-val :lambda-list '(m))
(cl:defmethod current_count-val ((m <demoFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader hello-msg:current_count-val is deprecated.  Use hello-msg:current_count instead.")
  (current_count m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <demoFeedback>) ostream)
  "Serializes a message object of type '<demoFeedback>"
  (cl:let* ((signed (cl:slot-value msg 'current_count)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <demoFeedback>) istream)
  "Deserializes a message object of type '<demoFeedback>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'current_count) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<demoFeedback>)))
  "Returns string type for a message object of type '<demoFeedback>"
  "hello/demoFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'demoFeedback)))
  "Returns string type for a message object of type 'demoFeedback"
  "hello/demoFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<demoFeedback>)))
  "Returns md5sum for a message object of type '<demoFeedback>"
  "f77169e65b5b24a984cd3f9acb1e49b5")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'demoFeedback)))
  "Returns md5sum for a message object of type 'demoFeedback"
  "f77169e65b5b24a984cd3f9acb1e49b5")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<demoFeedback>)))
  "Returns full string definition for message of type '<demoFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#part3: the feedback message, to be sent by server during execution~%int32 current_count~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'demoFeedback)))
  "Returns full string definition for message of type 'demoFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#part3: the feedback message, to be sent by server during execution~%int32 current_count~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <demoFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <demoFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'demoFeedback
    (cl:cons ':current_count (current_count msg))
))
