// Generated by gencpp from file hello/demoResult.msg
// DO NOT EDIT!


#ifndef HELLO_MESSAGE_DEMORESULT_H
#define HELLO_MESSAGE_DEMORESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hello
{
template <class ContainerAllocator>
struct demoResult_
{
  typedef demoResult_<ContainerAllocator> Type;

  demoResult_()
    : final_count(0)  {
    }
  demoResult_(const ContainerAllocator& _alloc)
    : final_count(0)  {
  (void)_alloc;
    }



   typedef int32_t _final_count_type;
  _final_count_type final_count;





  typedef boost::shared_ptr< ::hello::demoResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hello::demoResult_<ContainerAllocator> const> ConstPtr;

}; // struct demoResult_

typedef ::hello::demoResult_<std::allocator<void> > demoResult;

typedef boost::shared_ptr< ::hello::demoResult > demoResultPtr;
typedef boost::shared_ptr< ::hello::demoResult const> demoResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hello::demoResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hello::demoResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hello::demoResult_<ContainerAllocator1> & lhs, const ::hello::demoResult_<ContainerAllocator2> & rhs)
{
  return lhs.final_count == rhs.final_count;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hello::demoResult_<ContainerAllocator1> & lhs, const ::hello::demoResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hello

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::hello::demoResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hello::demoResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hello::demoResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hello::demoResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hello::demoResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hello::demoResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hello::demoResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eaae876f57686d9f2a92f60bfbd26c85";
  }

  static const char* value(const ::hello::demoResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeaae876f57686d9fULL;
  static const uint64_t static_value2 = 0x2a92f60bfbd26c85ULL;
};

template<class ContainerAllocator>
struct DataType< ::hello::demoResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hello/demoResult";
  }

  static const char* value(const ::hello::demoResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hello::demoResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#part2: the result message, to be sent by the server upon completion\n"
"int32 final_count\n"
;
  }

  static const char* value(const ::hello::demoResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hello::demoResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.final_count);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct demoResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hello::demoResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hello::demoResult_<ContainerAllocator>& v)
  {
    s << indent << "final_count: ";
    Printer<int32_t>::stream(s, indent + "  ", v.final_count);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HELLO_MESSAGE_DEMORESULT_H
