// Generated by gencpp from file hello/ser.msg
// DO NOT EDIT!


#ifndef HELLO_MESSAGE_SER_H
#define HELLO_MESSAGE_SER_H

#include <ros/service_traits.h>


#include <hello/serRequest.h>
#include <hello/serResponse.h>


namespace hello
{

struct ser
{

typedef serRequest Request;
typedef serResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ser
} // namespace hello


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hello::ser > {
  static const char* value()
  {
    return "4a5b2215d3a4f1a449d3560719406531";
  }

  static const char* value(const ::hello::ser&) { return value(); }
};

template<>
struct DataType< ::hello::ser > {
  static const char* value()
  {
    return "hello/ser";
  }

  static const char* value(const ::hello::ser&) { return value(); }
};


// service_traits::MD5Sum< ::hello::serRequest> should match
// service_traits::MD5Sum< ::hello::ser >
template<>
struct MD5Sum< ::hello::serRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hello::ser >::value();
  }
  static const char* value(const ::hello::serRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hello::serRequest> should match
// service_traits::DataType< ::hello::ser >
template<>
struct DataType< ::hello::serRequest>
{
  static const char* value()
  {
    return DataType< ::hello::ser >::value();
  }
  static const char* value(const ::hello::serRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hello::serResponse> should match
// service_traits::MD5Sum< ::hello::ser >
template<>
struct MD5Sum< ::hello::serResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hello::ser >::value();
  }
  static const char* value(const ::hello::serResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hello::serResponse> should match
// service_traits::DataType< ::hello::ser >
template<>
struct DataType< ::hello::serResponse>
{
  static const char* value()
  {
    return DataType< ::hello::ser >::value();
  }
  static const char* value(const ::hello::serResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HELLO_MESSAGE_SER_H
